http-server:
  port: 5003
cbir-component:
  dimension: 46704
  feature-files:
    - features/wkf/xaa.txt
    - features/wkf/xab.txt
    - features/wkf/xac.txt
    - features/wkf/xad.txt
    - features/wkf/xae.txt
    - features/wkf/xaf.txt
    - features/wkf/xag.txt
    - features/wkf/xah.txt
    - features/wkf/xai.txt
    - features/wkf/xaj.txt
    - features/wkf/xak.txt
    - features/wkf/xal.txt
    - features/wkf/xam.txt
  filter-files:
  sample-files:
